name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v**

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    uses: tryAGI/workflows/.github/workflows/generated-sdk-publish.yml@main
    with:
      auto-stable-release: true
      project-path: src/libs/YandexSpeechKit/YandexSpeechKit.csproj
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
